language: node_js
node_js:
  - 14
install:
  - echo "build FrontEnd"
  - cd client 
  - npm install
  - travis_retry npm install
  - npm run build
  - echo "build BackEnd"
  - cd ../backend
  - npm install
  - travis_retry npm install
script:
  - echo "deploy BackEnd"
  - npm install -g serverless
  - sls deploy -v
  - echo "deploy FrontEnd"
  - sls client deploy --no-confirm