language: node_js
node_js:
  - 14
script:
  - cd client 
  - npm install
  - travis_retry npm install
  - npm run build
  - cd ../backend
  - travis_retry npm install
deploy:
  provider: script
  skip_cleanup: true
  script: sls deploy -v && sls client deploy --no-confirm # Deploy using the Serverless Framework